### ISSUE TITLE
UX/UI suggestions for the ar.page profile edit feature

### ISSUE THREAD

**Issue by charmful0x** [nanofuxion/ANS_UI#3]
My comments on the current edit feature UI/UX so far are:

- Popup a box (like `sweetalert`) when the user broadcasts TX (after hitting `submit`)
- Highlight what every box input is about (like a `?` hover)
- Instead of submitting `pfp` as TXID (for the avatar), replace it with `upload` image method (similar to [Permacast's](https://permacast.net) podcasts cover)
- Validate input according to the [ANS SWC limitations](https://github.com/decentldotland/ANS/blob/main/contracts/ans.js#L236) before submitting the edit TX. And alert the error when it occurs.
- Halt the editing operation when the user's wallet have zero AR 
- Add `close` or `cancel` or an upper-right `X` button to close the edit component.
- Add support Twitter metadata for rendering a proper summary when a profile URL is shared.

Thank you!

**Comment by nanofuxion** [comment]
#4        fixes all but the last bullet. 
Last bullet fixed in [782bb9c](https://github.com/nanofuxion/ANS_UI/commit/782bb9c17e6a6206a33717e5f62acdb6be9233dc)
